"""
Cowrie Honeypot Configuration
Auto-generated by Quick Start
"""

COWRIE_HOST = "18.206.99.103"
COWRIE_USER = "ubuntu"
COWRIE_KEY = "cowrie-key.pem"
COWRIE_LOG_PATH = "/home/ubuntu/cowrie/var/log/cowrie/cowrie.json"
