"""
Cowrie Honeypot Configuration
Auto-generated by Quick Start
"""

COWRIE_HOST = "34.239.137.145"
COWRIE_USER = "ubuntu"
COWRIE_KEY = "cowrie_key.pem"
COWRIE_LOG_PATH = "/home/ubuntu/cowrie/var/log/cowrie/cowrie.json"
